# Generated by Django 5.2.4 on 2025-07-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(),
        ),
    ]
