# Generated by Django 5.2.4 on 2025-07-21 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='data_posted',
        ),
        migrations.AddField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
